name: CI Pipeline for AI Agent Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the required Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure this file has required dependencies

      - name: Install Chrome and ChromeDriver
        run: |
          # Update and install dependencies
          sudo apt-get update
          sudo apt-get install -y wget unzip curl
            
          # Install Google Chrome
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
            
          # Download specific ChromeDriver version
          wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Prepare Test Reports Directory
        run: |
          mkdir -p reports  # Create reports directory if not exists

      - name: Run Tests with Behave
        run: |
          behave -f pretty -o reports/pretty_report.txt
          behave -f behave_html_formatter:HTMLFormatter -o reports/AI_agent_report.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
